//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTilausDBJaanaPusa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top10Myynti
    {
        public long RiviID { get; set; }
        public Nullable<int> TuoteID { get; set; }
        public string Tuotenimi { get; set; }
        public Nullable<decimal> Myynti { get; set; }
    }
}
